$(function () {
	for(var i=0; data.length > i; i++) {
		if (data[i].winner_1.length > 0) {
			var winner_1 = {};
				winner_1.name = data[i].winner;
			var winner_2 = {};
				winner_2.name = data[i].winner_1;
			var loser_1 = {};
				loser_1.name = data[i].loser;
			var loser_2 = {};
				loser_2.name = data[i].loser_1;

			data[i].winner = [];
			data[i].winner.push(winner_1, winner_2);
			data[i].loser = [];
			data[i].loser.push(loser_1, loser_2);
			delete data[i].winner_1;
			delete data[i].loser_1;
		} else {
			var winner = {};
				winner.name = data[i].winner;
			var loser = {};
				loser.name = data[i].loser;
			data[i].winner = [];
			data[i].winner.push(winner);
			data[i].loser = [];
			data[i].loser.push(loser);
			delete data[i].winner_1;
			delete data[i].loser_1;
		}
	}
	var full_data = [];
	var curr_series = {};
		curr_series.series = [];
	var curr_series_id = 1;
	for(var j=0; data.length > j; j++) {
		console.log(curr_series_id);
		if (data[j].series_id > curr_series_id) {
			curr_series.winner = curr_series.series[0].winner;
			curr_series.loser = curr_series.series[0].loser;
			curr_series.series_id = curr_series_id;
			for(var q=0; curr_series.series.length > q; q++) {
				delete curr_series.series[q].series_id;
				delete curr_series.series[q].winner;
				delete curr_series.series[q].loser;
			}
			full_data.push(curr_series);
			curr_series_id = data[j].series_id;
			curr_series = {};
			curr_series.series = [];
		} else {
			curr_series.series.push(data[j]);
		}
	}
		var james = '52f2865196aea74f5a6ee2c7';
		var jon = '52f286cb96aea74f5a6ee2c9';
		var mike = "52f2866496aea74f5a6ee2c8";
		var tim = "52f2873a96aea74f5a6ee2cf";
		var meg = "52f286dd96aea74f5a6ee2ca";
		var david = "52f2872996aea74f5a6ee2ce";
		var eric = "52f2870e96aea74f5a6ee2cc";
		var christine = "52f286f296aea74f5a6ee2cb";
		var steve = "52f2871d96aea74f5a6ee2cd";
		var sam = "52f2875496aea74f5a6ee2d0";
	for(var i=0; full_data.length > i; i++) {
		_.each(full_data[i].loser, function(person) {
			if (person.name == 'jon') {
				person.id = jon;
			} else if (person.name == 'james') {
				person.id = james;
			} else if (person.name == 'mike') {
				person.id = mike;
			} else if (person.name == 'tim') {
				person.id = tim;
			} else if (person.name == 'meg') {
				person.id = meg;
			} else if (person.name == 'david') {
				person.id = david;
			} else if (person.name == 'eric') {
				person.id = eric;
			} else if (person.name == 'christine') {
				person.id = christine;
			} else if (person.name == 'steve') {
				person.id = steve;
			} else if (person.name == 'sam') {
				person.id = sam;
			}
		});
		_.each(full_data[i].winner, function(person) {
			if (person.name == 'jon') {
				person.id = jon;
			} else if (person.name == 'james') {
				person.id = james;
			} else if (person.name == 'mike') {
				person.id = mike;
			} else if (person.name == 'tim') {
				person.id = tim;
			} else if (person.name == 'meg') {
				person.id = meg;
			} else if (person.name == 'david') {
				person.id = david;
			} else if (person.name == 'eric') {
				person.id = eric;
			} else if (person.name == 'christine') {
				person.id = christine;
			} else if (person.name == 'steve') {
				person.id = steve;
			} else if (person.name == 'sam') {
				person.id = sam;
			}
		});
	}
	console.log(full_data);
	var json_data = JSON.stringify(full_data);
	console.log(json_data);
	// $.ajax({
	// 	type: 'POST',
	// 	// async: false,
	// 	url: '/api/insertCSV',
	// 	data: json_data,
	// 	dataType: 'json',
	// 	success: function (data) {
	// 		console.log('done');
	// 	}
	// });
});

var data = [
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":21,
    "score_loser":23,
    "game_type":21,
    "series_id":1
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":21,
    "score_loser":15,
    "game_type":21,
    "series_id":1
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":21,
    "score_loser":13,
    "game_type":21,
    "series_id":1
  },
  {
    "winner":"meg",
    "winner_1":"tim",
    "loser":"david",
    "loser_1":"eric",
    "score_winner":18,
    "score_loser":21,
    "game_type":21,
    "series_id":2
  },
  {
    "winner":"meg",
    "winner_1":"tim",
    "loser":"david",
    "loser_1":"eric",
    "score_winner":21,
    "score_loser":15,
    "game_type":21,
    "series_id":2
  },
  {
    "winner":"meg",
    "winner_1":"tim",
    "loser":"david",
    "loser_1":"eric",
    "score_winner":21,
    "score_loser":16,
    "game_type":21,
    "series_id":2
  },
  {
    "winner":"mike",
    "winner_1":"",
    "loser":"david",
    "loser_1":"",
    "score_winner":11,
    "score_loser":7,
    "game_type":11,
    "series_id":3
  },
  {
    "winner":"mike",
    "winner_1":"",
    "loser":"david",
    "loser_1":"",
    "score_winner":13,
    "score_loser":11,
    "game_type":11,
    "series_id":3
  },
  {
    "winner":"mike",
    "winner_1":"",
    "loser":"david",
    "loser_1":"",
    "score_winner":14,
    "score_loser":12,
    "game_type":11,
    "series_id":3
  },
  {
    "winner":"mike",
    "winner_1":"",
    "loser":"david",
    "loser_1":"",
    "score_winner":11,
    "score_loser":9,
    "game_type":11,
    "series_id":3
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":7,
    "score_loser":11,
    "game_type":11,
    "series_id":4
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":11,
    "score_loser":9,
    "game_type":11,
    "series_id":4
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":10,
    "score_loser":12,
    "game_type":11,
    "series_id":4
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":12,
    "score_loser":10,
    "game_type":11,
    "series_id":4
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":7,
    "score_loser":11,
    "game_type":11,
    "series_id":4
  },
  {
    "winner":"mike",
    "winner_1":"",
    "loser":"david",
    "loser_1":"",
    "score_winner":21,
    "score_loser":4,
    "game_type":21,
    "series_id":5
  },
  {
    "winner":"mike",
    "winner_1":"",
    "loser":"david",
    "loser_1":"",
    "score_winner":21,
    "score_loser":17,
    "game_type":21,
    "series_id":5
  },
  {
    "winner":"mike",
    "winner_1":"",
    "loser":"david",
    "loser_1":"",
    "score_winner":21,
    "score_loser":10,
    "game_type":21,
    "series_id":5
  },
  {
    "winner":"james",
    "winner_1":"",
    "loser":"jon",
    "loser_1":"",
    "score_winner":9,
    "score_loser":11,
    "game_type":11,
    "series_id":6
  },
  {
    "winner":"james",
    "winner_1":"",
    "loser":"jon",
    "loser_1":"",
    "score_winner":8,
    "score_loser":11,
    "game_type":11,
    "series_id":6
  },
  {
    "winner":"james",
    "winner_1":"",
    "loser":"jon",
    "loser_1":"",
    "score_winner":11,
    "score_loser":6,
    "game_type":11,
    "series_id":6
  },
  {
    "winner":"james",
    "winner_1":"",
    "loser":"jon",
    "loser_1":"",
    "score_winner":11,
    "score_loser":9,
    "game_type":11,
    "series_id":6
  },
  {
    "winner":"james",
    "winner_1":"",
    "loser":"jon",
    "loser_1":"",
    "score_winner":15,
    "score_loser":17,
    "game_type":11,
    "series_id":6
  },
  {
    "winner":"james",
    "winner_1":"jon",
    "loser":"eric",
    "loser_1":"tim",
    "score_winner":21,
    "score_loser":11,
    "game_type":21,
    "series_id":7
  },
  {
    "winner":"james",
    "winner_1":"jon",
    "loser":"eric",
    "loser_1":"tim",
    "score_winner":21,
    "score_loser":23,
    "game_type":21,
    "series_id":7
  },
  {
    "winner":"james",
    "winner_1":"jon",
    "loser":"eric",
    "loser_1":"tim",
    "score_winner":21,
    "score_loser":19,
    "game_type":21,
    "series_id":7
  },
  {
    "winner":"tim",
    "winner_1":"",
    "loser":"eric",
    "loser_1":"",
    "score_winner":9,
    "score_loser":11,
    "game_type":11,
    "series_id":8
  },
  {
    "winner":"tim",
    "winner_1":"",
    "loser":"eric",
    "loser_1":"",
    "score_winner":9,
    "score_loser":11,
    "game_type":11,
    "series_id":8
  },
  {
    "winner":"tim",
    "winner_1":"",
    "loser":"eric",
    "loser_1":"",
    "score_winner":11,
    "score_loser":9,
    "game_type":11,
    "series_id":8
  },
  {
    "winner":"tim",
    "winner_1":"",
    "loser":"eric",
    "loser_1":"",
    "score_winner":4,
    "score_loser":11,
    "game_type":11,
    "series_id":8
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"tim",
    "loser_1":"",
    "score_winner":11,
    "score_loser":6,
    "game_type":11,
    "series_id":9
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"tim",
    "loser_1":"",
    "score_winner":11,
    "score_loser":9,
    "game_type":11,
    "series_id":9
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"tim",
    "loser_1":"",
    "score_winner":11,
    "score_loser":9,
    "game_type":11,
    "series_id":9
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"tim",
    "loser_1":"",
    "score_winner":11,
    "score_loser":8,
    "game_type":11,
    "series_id":9
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"tim",
    "loser_1":"",
    "score_winner":11,
    "score_loser":6,
    "game_type":11,
    "series_id":9
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"tim",
    "loser_1":"",
    "score_winner":11,
    "score_loser":9,
    "game_type":11,
    "series_id":9
  },
  {
    "winner":"james",
    "winner_1":"jon",
    "loser":"meg",
    "loser_1":"tim",
    "score_winner":21,
    "score_loser":13,
    "game_type":21,
    "series_id":10
  },
  {
    "winner":"james",
    "winner_1":"jon",
    "loser":"meg",
    "loser_1":"tim",
    "score_winner":21,
    "score_loser":17,
    "game_type":21,
    "series_id":10
  },
  {
    "winner":"meg",
    "winner_1":"tim",
    "loser":"james",
    "loser_1":"jon",
    "score_winner":6,
    "score_loser":11,
    "game_type":11,
    "series_id":11
  },
  {
    "winner":"meg",
    "winner_1":"tim",
    "loser":"james",
    "loser_1":"jon",
    "score_winner":7,
    "score_loser":11,
    "game_type":11,
    "series_id":11
  },
  {
    "winner":"meg",
    "winner_1":"tim",
    "loser":"james",
    "loser_1":"jon",
    "score_winner":5,
    "score_loser":11,
    "game_type":11,
    "series_id":11
  },
  {
    "winner":"mike",
    "winner_1":"tim",
    "loser":"james",
    "loser_1":"jon",
    "score_winner":21,
    "score_loser":18,
    "game_type":21,
    "series_id":12
  },
  {
    "winner":"mike",
    "winner_1":"tim",
    "loser":"james",
    "loser_1":"jon",
    "score_winner":21,
    "score_loser":17,
    "game_type":21,
    "series_id":12
  },
  {
    "winner":"mike",
    "winner_1":"tim",
    "loser":"steve",
    "loser_1":"eric",
    "score_winner":21,
    "score_loser":11,
    "game_type":21,
    "series_id":13
  },
  {
    "winner":"mike",
    "winner_1":"tim",
    "loser":"steve",
    "loser_1":"eric",
    "score_winner":21,
    "score_loser":18,
    "game_type":21,
    "series_id":13
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"tim",
    "loser_1":"",
    "score_winner":21,
    "score_loser":18,
    "game_type":21,
    "series_id":14
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"tim",
    "loser_1":"",
    "score_winner":18,
    "score_loser":21,
    "game_type":21,
    "series_id":14
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"tim",
    "loser_1":"",
    "score_winner":21,
    "score_loser":8,
    "game_type":21,
    "series_id":14
  },
  {
    "winner":"david",
    "winner_1":"meg",
    "loser":"eric",
    "loser_1":"steve",
    "score_winner":15,
    "score_loser":21,
    "game_type":21,
    "series_id":15
  },
  {
    "winner":"david",
    "winner_1":"meg",
    "loser":"eric",
    "loser_1":"steve",
    "score_winner":13,
    "score_loser":21,
    "game_type":21,
    "series_id":15
  },
  {
    "winner":"david",
    "winner_1":"meg",
    "loser":"eric",
    "loser_1":"steve",
    "score_winner":8,
    "score_loser":21,
    "game_type":21,
    "series_id":15
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":11,
    "score_loser":9,
    "game_type":11,
    "series_id":16
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":10,
    "score_loser":12,
    "game_type":11,
    "series_id":16
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":11,
    "score_loser":5,
    "game_type":11,
    "series_id":16
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":11,
    "score_loser":6,
    "game_type":11,
    "series_id":17
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":6,
    "score_loser":11,
    "game_type":11,
    "series_id":17
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":7,
    "score_loser":11,
    "game_type":11,
    "series_id":17
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":5,
    "score_loser":11,
    "game_type":11,
    "series_id":17
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":24,
    "score_loser":26,
    "game_type":21,
    "series_id":18
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":24,
    "score_loser":22,
    "game_type":21,
    "series_id":18
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":21,
    "score_loser":18,
    "game_type":21,
    "series_id":18
  },
  {
    "winner":"james",
    "winner_1":"",
    "loser":"christine",
    "loser_1":"",
    "score_winner":11,
    "score_loser":8,
    "game_type":11,
    "series_id":19
  },
  {
    "winner":"james",
    "winner_1":"",
    "loser":"christine",
    "loser_1":"",
    "score_winner":11,
    "score_loser":6,
    "game_type":11,
    "series_id":19
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":21,
    "score_loser":15,
    "game_type":21,
    "series_id":20
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":17,
    "score_loser":21,
    "game_type":21,
    "series_id":20
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":21,
    "score_loser":16,
    "game_type":21,
    "series_id":20
  },
  {
    "winner":"james",
    "winner_1":"jon",
    "loser":"mike",
    "loser_1":"christine",
    "score_winner":22,
    "score_loser":24,
    "game_type":21,
    "series_id":21
  },
  {
    "winner":"james",
    "winner_1":"jon",
    "loser":"mike",
    "loser_1":"christine",
    "score_winner":21,
    "score_loser":14,
    "game_type":21,
    "series_id":21
  },
  {
    "winner":"james",
    "winner_1":"jon",
    "loser":"mike",
    "loser_1":"christine",
    "score_winner":21,
    "score_loser":17,
    "game_type":21,
    "series_id":21
  },
  {
    "winner":"david",
    "winner_1":"",
    "loser":"mike",
    "loser_1":"",
    "score_winner":14,
    "score_loser":21,
    "game_type":21,
    "series_id":22
  },
  {
    "winner":"david",
    "winner_1":"",
    "loser":"mike",
    "loser_1":"",
    "score_winner":10,
    "score_loser":21,
    "game_type":21,
    "series_id":22
  },
  {
    "winner":"david",
    "winner_1":"",
    "loser":"mike",
    "loser_1":"",
    "score_winner":17,
    "score_loser":21,
    "game_type":21,
    "series_id":22
  },
  {
    "winner":"mike",
    "winner_1":"christine",
    "loser":"james",
    "loser_1":"eric",
    "score_winner":21,
    "score_loser":14,
    "game_type":21,
    "series_id":23
  },
  {
    "winner":"mike",
    "winner_1":"christine",
    "loser":"james",
    "loser_1":"eric",
    "score_winner":21,
    "score_loser":14,
    "game_type":21,
    "series_id":23
  },
  {
    "winner":"mike",
    "winner_1":"james",
    "loser":"eric",
    "loser_1":"meg",
    "score_winner":21,
    "score_loser":14,
    "game_type":21,
    "series_id":24
  },
  {
    "winner":"mike",
    "winner_1":"james",
    "loser":"eric",
    "loser_1":"meg",
    "score_winner":21,
    "score_loser":13,
    "game_type":21,
    "series_id":24
  },
  {
    "winner":"tim",
    "winner_1":"christine",
    "loser":"eric",
    "loser_1":"meg",
    "score_winner":20,
    "score_loser":22,
    "game_type":21,
    "series_id":24
  },
  {
    "winner":"tim",
    "winner_1":"christine",
    "loser":"eric",
    "loser_1":"meg",
    "score_winner":15,
    "score_loser":21,
    "game_type":21,
    "series_id":24
  },
  {
    "winner":"eric",
    "winner_1":"meg",
    "loser":"tim",
    "loser_1":"james",
    "score_winner":24,
    "score_loser":22,
    "game_type":21,
    "series_id":25
  },
  {
    "winner":"eric",
    "winner_1":"meg",
    "loser":"tim",
    "loser_1":"james",
    "score_winner":21,
    "score_loser":14,
    "game_type":21,
    "series_id":25
  },
  {
    "winner":"mike",
    "winner_1":"christine",
    "loser":"eric",
    "loser_1":"meg",
    "score_winner":24,
    "score_loser":22,
    "game_type":21,
    "series_id":26
  },
  {
    "winner":"mike",
    "winner_1":"christine",
    "loser":"eric",
    "loser_1":"meg",
    "score_winner":16,
    "score_loser":21,
    "game_type":21,
    "series_id":26
  },
  {
    "winner":"mike",
    "winner_1":"christine",
    "loser":"eric",
    "loser_1":"meg",
    "score_winner":21,
    "score_loser":6,
    "game_type":21,
    "series_id":26
  },
  {
    "winner":"mike",
    "winner_1":"christine",
    "loser":"james",
    "loser_1":"tim",
    "score_winner":21,
    "score_loser":18,
    "game_type":21,
    "series_id":27
  },
  {
    "winner":"mike",
    "winner_1":"christine",
    "loser":"james",
    "loser_1":"tim",
    "score_winner":17,
    "score_loser":21,
    "game_type":21,
    "series_id":27
  },
  {
    "winner":"mike",
    "winner_1":"christine",
    "loser":"james",
    "loser_1":"tim",
    "score_winner":21,
    "score_loser":16,
    "game_type":21,
    "series_id":27
  },
  {
    "winner":"tim",
    "winner_1":"",
    "loser":"eric",
    "loser_1":"",
    "score_winner":22,
    "score_loser":24,
    "game_type":21,
    "series_id":28
  },
  {
    "winner":"tim",
    "winner_1":"",
    "loser":"eric",
    "loser_1":"",
    "score_winner":16,
    "score_loser":21,
    "game_type":21,
    "series_id":28
  },
  {
    "winner":"tim",
    "winner_1":"",
    "loser":"eric",
    "loser_1":"",
    "score_winner":12,
    "score_loser":21,
    "game_type":21,
    "series_id":28
  },
  {
    "winner":"david",
    "winner_1":"",
    "loser":"mike",
    "loser_1":"",
    "score_winner":15,
    "score_loser":21,
    "game_type":21,
    "series_id":29
  },
  {
    "winner":"david",
    "winner_1":"",
    "loser":"mike",
    "loser_1":"",
    "score_winner":14,
    "score_loser":21,
    "game_type":21,
    "series_id":29
  },
  {
    "winner":"david",
    "winner_1":"",
    "loser":"mike",
    "loser_1":"",
    "score_winner":16,
    "score_loser":21,
    "game_type":21,
    "series_id":29
  },
  {
    "winner":"david",
    "winner_1":"",
    "loser":"steve",
    "loser_1":"",
    "score_winner":21,
    "score_loser":19,
    "game_type":21,
    "series_id":30
  },
  {
    "winner":"david",
    "winner_1":"",
    "loser":"steve",
    "loser_1":"",
    "score_winner":14,
    "score_loser":21,
    "game_type":21,
    "series_id":30
  },
  {
    "winner":"david",
    "winner_1":"",
    "loser":"steve",
    "loser_1":"",
    "score_winner":21,
    "score_loser":11,
    "game_type":21,
    "series_id":30
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"mike",
    "loser_1":"",
    "score_winner":8,
    "score_loser":11,
    "game_type":11,
    "series_id":31
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"mike",
    "loser_1":"",
    "score_winner":5,
    "score_loser":11,
    "game_type":11,
    "series_id":31
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"mike",
    "loser_1":"",
    "score_winner":11,
    "score_loser":7,
    "game_type":11,
    "series_id":31
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"mike",
    "loser_1":"",
    "score_winner":3,
    "score_loser":11,
    "game_type":11,
    "series_id":31
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"tim",
    "loser_1":"",
    "score_winner":23,
    "score_loser":21,
    "game_type":21,
    "series_id":32
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"tim",
    "loser_1":"",
    "score_winner":18,
    "score_loser":21,
    "game_type":21,
    "series_id":32
  },
  {
    "winner":"eric",
    "winner_1":"",
    "loser":"tim",
    "loser_1":"",
    "score_winner":21,
    "score_loser":14,
    "game_type":21,
    "series_id":32
  },
  {
    "winner":"steve",
    "winner_1":"",
    "loser":"eric",
    "loser_1":"",
    "score_winner":18,
    "score_loser":21,
    "game_type":21,
    "series_id":33
  },
  {
    "winner":"steve",
    "winner_1":"",
    "loser":"eric",
    "loser_1":"",
    "score_winner":21,
    "score_loser":16,
    "game_type":21,
    "series_id":33
  },
  {
    "winner":"steve",
    "winner_1":"",
    "loser":"eric",
    "loser_1":"",
    "score_winner":21,
    "score_loser":14,
    "game_type":21,
    "series_id":33
  },
  {
    "winner":"steve",
    "winner_1":"",
    "loser":"eric",
    "loser_1":"",
    "score_winner":18,
    "score_loser":21,
    "game_type":21,
    "series_id":33
  },
  {
    "winner":"steve",
    "winner_1":"",
    "loser":"eric",
    "loser_1":"",
    "score_winner":15,
    "score_loser":21,
    "game_type":21,
    "series_id":33
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":23,
    "score_loser":21,
    "game_type":21,
    "series_id":34
  },
  {
    "winner":"jon",
    "winner_1":"",
    "loser":"james",
    "loser_1":"",
    "score_winner":21,
    "score_loser":12,
    "game_type":21,
    "series_id":34
  },
  {
    "winner":"james",
    "winner_1":"christine",
    "loser":"meg",
    "loser_1":"david",
    "score_winner":21,
    "score_loser":17,
    "game_type":21,
    "series_id":35
  },
  {
    "winner":"james",
    "winner_1":"christine",
    "loser":"meg",
    "loser_1":"david",
    "score_winner":14,
    "score_loser":21,
    "game_type":21,
    "series_id":35
  },
  {
    "winner":"james",
    "winner_1":"christine",
    "loser":"meg",
    "loser_1":"david",
    "score_winner":21,
    "score_loser":14,
    "game_type":21,
    "series_id":35
  },
  {
    "winner":"mike",
    "winner_1":"tim",
    "loser":"james",
    "loser_1":"jon",
    "score_winner":14,
    "score_loser":21,
    "game_type":21,
    "series_id":37
  },
  {
    "winner":"mike",
    "winner_1":"tim",
    "loser":"james",
    "loser_1":"jon",
    "score_winner":21,
    "score_loser":14,
    "game_type":21,
    "series_id":37
  },
  {
    "winner":"mike",
    "winner_1":"tim",
    "loser":"james",
    "loser_1":"jon",
    "score_winner":23,
    "score_loser":21,
    "game_type":21,
    "series_id":37
  },
  {
    "winner":"mike",
    "winner_1":"christine",
    "loser":"james",
    "loser_1":"eric",
    "score_winner":21,
    "score_loser":11,
    "game_type":21,
    "series_id":38
  },
  {
    "winner":"mike",
    "winner_1":"christine",
    "loser":"james",
    "loser_1":"eric",
    "score_winner":21,
    "score_loser":6,
    "game_type":21,
    "series_id":38
  }
]